[package]
name = "AdventOfCode24"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
itertools = "0.13.0"
progressing = "3.0.2"
log = "0.4.22"
env_logger = "0.11.5"
rayon = "1.10"
cached = "0.54.0"
good_lp = {version = "1.10.0", features = ["highs"], default-features = false}